apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: resource-group
  description: Módulo no-code para criação de "resource-group"
spec:
  type: terraform-module
  name: resource-group
  owner: squad-automacao
  lifecycle: production
  definition:
    input:
      - azurerm_database_name
      - azurerm_key_vault_access_policy_name
      - azurerm_key_vault_access_policy_object_id
      - azurerm_key_vault_name
      - azurerm_redis_cache_name
      - azurerm_resource_group_location
      - azurerm_resource_group_name
      - azurerm_storage_account_name
      - tags
    output:
      - resource_group_location
      - resource_group_location_tes02rvvs
      - resource_group_location_tes0rsv3
      - resource_group_name
      - resource_group_name_rvsfa
    dependsOn:
      - resource: terraform-azurerm-rvs-redis-cache
      - resource: terraform-azurerm-rvs-storage-account
      - resource: terraform-azurerm-srv-key-vault
      - resource: terraform-azurerm-tdr-database
      - resource: terraform-azurerm-tdr-key-vault-access-policy
